/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.statistics;

import frontend.GameSummary;
import frontend.animator.AnimatorWindow;
import javax.swing.JTable;
import npuzzle.Board;

/**
 *
 * @author Lalu
 */
public class StatisticsWindow extends javax.swing.JFrame {

    private StatisticsWindowController statisticsController;

    /**
     * Creates new form StatisticsWindow
     */
    public StatisticsWindow() {
        initComponents();
        statisticsController = new StatisticsWindowController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        setTheBoardSizeLabel = new javax.swing.JLabel();
        rowsLabel = new javax.swing.JLabel();
        columnsLabel = new javax.swing.JLabel();
        loadStatisticsButton = new javax.swing.JButton();
        animateButton = new javax.swing.JButton();
        rowsNumberComboBox = new javax.swing.JComboBox<>();
        columnsNumberComboBox = new javax.swing.JComboBox<>();
        informationLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statisticsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Statistics");

        setTheBoardSizeLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        setTheBoardSizeLabel.setText("Set the board size");

        rowsLabel.setText("rows");

        columnsLabel.setText("columns");

        loadStatisticsButton.setText("load statistics");
		
        loadStatisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadStatisticsButtonActionPerformed(evt);
            }
        });

        animateButton.setText("animate");
		animateButton.setEnabled(false);
		animateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animateButtonActionPerformed(evt);
            }
        });
		
        rowsNumberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));

        columnsNumberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));

		informationLabel.setText(" ");
        informationLabel.setVisible(true);

        jScrollPane1.setViewportView(statisticsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(columnsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(columnsNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rowsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rowsNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(setTheBoardSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 108, Short.MAX_VALUE)
                        .addComponent(loadStatisticsButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(animateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(informationLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(setTheBoardSizeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rowsLabel)
                    .addComponent(rowsNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadStatisticsButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(columnsLabel)
                        .addComponent(columnsNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				
				.addGap(10, 10, 10)
                .addComponent(animateButton)
				.addGap(10, 10, 10)
                .addContainerGap())
        );

        pack();
    }

    private void loadStatisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {
        statisticsController.getSortedStatistics(Integer.parseInt(rowsNumberComboBox.getSelectedItem().toString()),
                Integer.parseInt(columnsNumberComboBox.getSelectedItem().toString()));
        if (statisticsController.getStatisticsList().isEmpty()) {
            informationLabel.setText("Unfortunatelly, there is no data for selected values!");
            informationLabel.setVisible(true);
        } else {
            createAndFillTable();
            statisticsTable.setVisible(true);
            informationLabel.setText("You can select a player and after clicking animate button animation window will appear.");
            informationLabel.setVisible(true);
            animateButton.setVisible(true);
        }
    }

    private void animateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int row = statisticsTable.getSelectedRow();
        GameSummary playerSummary = statisticsController.getStatisticsList().get(row);
        String winningPath = playerSummary.getSolution();
        String[] winningArray = winningPath.split(""); //change string to string array
        
        int[][] winningState = null;
        int counter = 0;
        for (int i = 0; i < playerSummary.getRows(); i++) {
            for (int j = 0; j < playerSummary.getColumns(); j++) {
                //winningState[i][j] = winningArray[counter];
                counter++;
            }
        }
        AnimatorWindow window = new AnimatorWindow(new Board(winningState), winningPath);
    }

    private javax.swing.JButton animateButton;
    private javax.swing.JLabel columnsLabel;
    private javax.swing.JComboBox<String> columnsNumberComboBox;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadStatisticsButton;
    private javax.swing.JLabel rowsLabel;
    private javax.swing.JComboBox<String> rowsNumberComboBox;
    private javax.swing.JLabel setTheBoardSizeLabel;
    private javax.swing.JTable statisticsTable;

    private void createAndFillTable() {
        statisticsTable = new JTable(statisticsController.getStatisticsList().size(), 3);
        for (int i = 0; i < statisticsController.getStatisticsList().size(); i++) {
            statisticsTable.getModel().setValueAt(statisticsController.getStatisticsList().get(i).getPlayerName(), i, 0);
            statisticsTable.getModel().setValueAt(statisticsController.getStatisticsList().get(i).getTime(), i, 1);
            statisticsTable.getModel().setValueAt(statisticsController.getStatisticsList().get(i).getStepsNumber(), i, 2);
        }
    }
}
